start:
	python bin/app.py 3333 &


clean:
	rm DPAF_damping_ratio.png
	rm DPAF_G_Gmax.png
	rm DPAF_strain_stress.png
	rm DPLH_damping_ratio.png
	rm DPLH_G_Gmax.png
	rm DPLH_strain_stress.png
	rm VMAF_damping_ratio.png
	rm VMAF_G_Gmax.png
	rm VMAF_strain_stress.png
	rm VMLH_damping_ratio.png
	rm VMLH_G_Gmax.png
	rm VMLH_strain_stress.png